---
title: "2018 EDA_Summary"
author: "Marty Simonson"
date: "November 12, 2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r,include=FALSE}
packages<-function(x, repos="http://cran.r-project.org", ...){
x<-as.character(match.call()[[2]])
if (!require(x,character.only=TRUE)){
install.packages(pkgs=x, repos=repos, ...)
require(x,character.only=TRUE)
}
}

#remove.packages(c("ggplot2", "data.table"))
#install.packages('Rcpp', dependencies = TRUE)
#install.packages('ggplot2', dependencies = TRUE)
#install.packages('data.table', dependencies = TRUE)

packages(rcompanion)
packages(vegan)
packages(ggplot2)
packages(gridExtra)
packages(reshape2)
packages(FSA)
packages(nnet)
#packages(multcomp)
packages(plyr)
#packages(rv)
#packages(arm)
packages(lattice)
packages(tikzDevice)
#packages(GGally)
packages(wesanderson)
#packages(DescTools)
#packages(mvnormtest)
#packages(HH)
#packages(biotools)
#packages(car)
#packages(psych)
#packages(GPArotation)
packages(doBy)
packages(dplyr)
```



# Load in data and summarize, look for glaring errors:
```{r}
data<-read.csv("2018_Data_compiled.csv",header=T)
headtail(data)

str(data)

###################
#
#     Data Management: Columns formatting
#
###################

# Date
levels(data$Date)
data$Date<-as.Date(data$Date, format = "%m/%d/%Y")
str(data$Date)


# Lake
summary(data$Lake)
data$Lake[data$Lake == "SIlver"] <- "Silver"
data$Lake[data$Lake == "silver"] <- "Silver"
data$Lake[data$Lake == "Silver (Dickinson)"] <- "Silver"
data$Lake[data$Lake == "Five Island"] <- "5 Island"
data$Lake[data$Lake == "N Twin"] <- "N. Twin"
data$Lake[data$Lake == "S Twin"] <- "S. Twin"
data$Lake<-droplevels(data$Lake)

# TAG.NUMBER - Already a factor
summary(data$TAG.NUMBER)
data$TAG.NUMBER[data$TAG.NUMBER == ""] <- NA # set non-tagged fish to NA
summary(data$TAG.NUMBER)
data$TAG.NUMBER<-droplevels(data$TAG.NUMBER)
    # still need to check NAs, and 7 fish captured 4 times

# Species
levels(data$Species) #KOI could be an issue, as with BMB and CAP for abbreviations
data$TAG.NUMBER[data$Species == "KOI"]
data$Lake[data$Species == "KOI"]
data$Species[data$Species == "KOI"] <- "COC"
data$Species[data$Species == "CAP"] <- "COC"
data$Species[data$Species == "BMB"] <- "BIB"
data$Species[data$Species == "YL Bass"] <- "YLB"
#data$Lake[data$Species == "YLB"]
data$Species<-droplevels(data$Species)
summary(data$Species)
# Confirm the abbreviations: Yellow Bullhead = YEB; Yellow Bass = YLB

# Length..mm.
str(data$Length..mm.)
data$Length..mm.[data$Length..mm. ==""] <- NA
data$Length..mm.[data$Length..mm. =="0"] <- NA
data$Length..mm.<-droplevels(data$Length..mm.)
data$Length..mm.<-as.numeric(as.character(data$Length..mm.))
str(data$Length..mm.)
summary(data$Length..mm.) 

# seems legit! only 33 missing values. 
# 
# Don't forget to put the character command within the numeric!


# Weight..g.
# Needs to be rounded to whole numbers
summary(data$Weight..g.[data$Species == "COC"])
summary(data$Weight..g.[data$Species == "BIB"]) # Maximum is good (30.6 lb buffalo in Storm)
summary(data$Weight..g.)
# Minimum is 10 (BLG in Blue)
data$Weight..g.<-round(data$Weight..g.) # set to just grams

#######
#
# Recap Column
#
summary(data$Recap)



```

# Silver Lake Carp Summary
```{r}
# Length Frequency Histogram of COC in Silver Lake, IA

silver.coc<-subset(data, Species == "COC")
silver.coc<-subset(silver.coc, Lake == "Silver")
silver.coc<-subset(silver.coc, !is.na(silver.coc$Length..mm.))
head(silver.coc)
str(silver.coc)

library(ggplot2)

ggplot(silver.coc, aes(x=Length..mm., fill=Species))+
  geom_histogram(binwidth=10,colour="black",position="dodge")+
  scale_x_continuous(limits = c(0,1000))+
  scale_y_continuous(limits = c(0,60))

library(rcompanion)
groupwiseMean(Length..mm.~1,
              data = silver.coc,
              conf = 0.95,
              digits = 3)

sem<-sd(silver.coc$Length..mm.)/sqrt(length(silver.coc$Length..mm.))

# cpue for coc in silver lake in june
#
# CarpCPUE - n fish per hour electrofishing
#
summary(silver.coc)
# on-time in seconds to Effort in hours
       # Need to remove seine hauls and NAs
str(silver.coc$On.Time..s.)
silver.coc$On.Time..s.[silver.coc$On.Time..s. == ""] <- NA
silver.coc$On.Time..s.[silver.coc$On.Time..s. == "453/488"] <- "941"
silver.coc$On.Time..s.<-as.numeric(as.character(silver.coc$On.Time..s.))
silver.coc$Effort<-silver.coc$On.Time..s./3600



# now to paste date, then lake then run
silver.coc$DR<-factor(paste(silver.coc$Date,silver.coc$Site.Transect))

# Now to divide the count of captured fish by the mean effort per DLR
coc.cpue<-aggregate(Effort~DR, data = silver.coc, mean, na.action=NULL)
silver.coc$dummy<-1
coc.n<-aggregate(dummy~DR, data = silver.coc, sum)
coc.cpue$n<-coc.n$dummy
coc.cpue$cpue<-coc.cpue$n/coc.cpue$Effort
coc.cpue<-coc.cpue[!is.na(coc.cpue$cpue),]

june.coc.cpue<-coc.cpue[c(12:44),]
groupwiseMean(cpue~1,
              data=june.coc.cpue,
              conf = 0.95)

```

# length-specific biomass estimates
subset lake first. then subsett with just COC and BIB, drop NAs


```{r,}
#Lakes
levels(data$Lake)
Blue <- subset(data, Lake == "Blue")
Center<-subset(data, Lake == "Center")
FiveIsland<-subset(data, Lake == "5 Island")
NTwin<-subset(data, Lake == "N. Twin")
Silver<-subset(data, Lake == "Silver")
STwin<-subset(data, Lake == "S. Twin")
Storm<-subset(data,Lake == "Storm")
```

# Blue
```{r,}
###########################
#
# Blue Lake
#
# Carp:
Blue.coc<-subset(Blue, Species =="COC")
Blue.coc<-subset(Blue.coc, !is.na(Blue.coc$Length..mm.))

#Buffalo not needed for Blue

#25mm bins
Blue.COC.25 <- Blue.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
Blue.COC.50 <- Blue.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
# so now we have percent frequency in 25/50mm (1-2") bins. Need to calculate average weight for those bins.
# I forsee my method taking too long but it's all I can think of right now:
#       to reduce repitition, let's go with the 50mm (2") bins first.
#       need 1 line of code to subset a new frame for each length bin, 
#       then take mean weight.

Blue.coc.temp<-subset(Blue.coc, Length..mm. >= 250 & Length..mm. < 300 & !is.na(Weight..g.))
w1<-mean(Blue.coc.temp$Weight..g.)

Blue.coc.temp<-subset(Blue.coc, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w2<-mean(Blue.coc.temp$Weight..g.)

Blue.coc.temp<-subset(Blue.coc, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w3<-mean(Blue.coc.temp$Weight..g.)

Blue.coc.temp<-subset(Blue.coc, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w4<-mean(Blue.coc.temp$Weight..g.)

Blue.coc.temp<-subset(Blue.coc, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w5<-mean(Blue.coc.temp$Weight..g.)

Blue.coc.temp<-subset(Blue.coc, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w6<-mean(Blue.coc.temp$Weight..g.)

Blue.coc.temp<-subset(Blue.coc, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w7<-mean(Blue.coc.temp$Weight..g.)

Blue.coc.temp<-subset(Blue.coc, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w8<-mean(Blue.coc.temp$Weight..g.)

Blue.coc.temp<-subset(Blue.coc, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w9<-mean(Blue.coc.temp$Weight..g.)

Blue.COC.50$mweight<-c(w2,w2,w3,w4,w5,w6,w7,w8,w9) # changed w1 to w2 for one fish below 300

#######
#
# Calculate the total weight through a sum of fractional weights
# 
# Blue Population Estimates: 60996 - 72140 - 83284
# Blue Lake area: 269 acres
#
# Convert to lbs
# convert to density
#
# Should end up with a list of 12 blue lake values 2x(L.BM,BM,U.BM,L.BMDensity,BMDensity,U.BMDensity)

Blue.COC.50$percent<-Blue.COC.50$percent/100 # percent to decimal

Blue.COC.50$LowerBM<-Blue.COC.50$percent * Blue.COC.50$mweight * 60996 # multiply fraction, mean weight, lower pop.
C.L.BM<-sum(Blue.COC.50$LowerBM/453.592)


Blue.COC.50$BMest<-Blue.COC.50$percent * Blue.COC.50$mweight * 72140 # multiply fraction, mean weight, pop. est
C.BM<-sum(Blue.COC.50$BMest/453.592)

Blue.COC.50$UpperBM<-Blue.COC.50$percent * Blue.COC.50$mweight * 83284 # multiply fraction, mean weight, upper pop.
C.U.BM<-sum(Blue.COC.50$UpperBM/453.592)

C.L.BMDensity<-C.L.BM/269
C.BMDensity<-C.BM/269
C.U.BMDensity<-C.U.BM/269

B.L.BM<-NA
B.BM<-NA
B.U.BM<-NA
B.L.BMDensity<-NA
B.BMDensity<-NA
B.U.BMDensity<-NA


Blue.BM.Density<-c(C.L.BM,C.BM,C.U.BM,C.L.BMDensity,C.BMDensity,C.U.BMDensity,
                   B.L.BM,B.BM,B.U.BM,B.L.BMDensity,B.BMDensity,B.U.BMDensity)


```

#Center
```{r,}

###########################
#
# Center Lake
#
# Carp:
Center.coc<-subset(Center, Species =="COC")
Center.coc<-subset(Center.coc, !is.na(Center.coc$Length..mm.))
#Buffalo
Center.bib<-subset(Center, Species =="BIB")
Center.bib<-subset(Center.bib, !is.na(Center.bib$Length..mm.))
#25mm bins
Center.COC.25 <- Center.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
Center.COC.50 <- Center.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
# so now we have percent frequency in 25/50mm (1-2") bins. Need to calculate average weight for those bins.
# I forsee my method taking too long but it's all I can think of right now:
#       to reduce repitition, let's go with the 50mm (2") bins first.
#       need 1 line of code to subset a new frame for each length bin, 
#       then take mean weight.

Center.coc.temp<-subset(Center.coc, Length..mm. >= 50 & Length..mm. < 100 & !is.na(Weight..g.))
w1<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 100 & Length..mm. < 150 & !is.na(Weight..g.))
w2<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 250 & Length..mm. < 300 & !is.na(Weight..g.))
w3<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w4<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w5<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w6<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w7<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w8<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w9<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w10<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w11<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w12<-mean(Center.coc.temp$Weight..g.)

Center.coc.temp<-subset(Center.coc, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w13<-mean(Center.coc.temp$Weight..g.)


Center.COC.50$mweight<-c(w5,w5,w5,w5,w5,w6,w7,w8,w9,w10,w11,w12,w13) #changed last two to w11 and first to w3 

# Now Buffalo

#25mm bins
Center.bib.25 <- Center.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
Center.bib.50 <- Center.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()

Center.bib.temp<-subset(Center.bib, Length..mm. >= 250 & Length..mm. < 300 & !is.na(Weight..g.))
w1<-mean(Center.bib.temp$Weight..g.)

Center.bib.temp<-subset(Center.bib, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w2<-mean(Center.bib.temp$Weight..g.)

Center.bib.temp<-subset(Center.bib, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w3<-mean(Center.bib.temp$Weight..g.)

Center.bib.temp<-subset(Center.bib, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w4<-mean(Center.bib.temp$Weight..g.)

Center.bib.temp<-subset(Center.bib, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w5<-mean(Center.bib.temp$Weight..g.)

Center.bib.temp<-subset(Center.bib, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w6<-mean(Center.bib.temp$Weight..g.)

Center.bib.temp<-subset(Center.bib, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w7<-mean(Center.bib.temp$Weight..g.)

Center.bib.temp<-subset(Center.bib, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w8<-mean(Center.bib.temp$Weight..g.)

Center.bib.temp<-subset(Center.bib, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w9<-mean(Center.bib.temp$Weight..g.)

Center.bib.temp<-subset(Center.bib, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w10<-mean(Center.bib.temp$Weight..g.)

Center.bib.50$mweight<-c(w3,w3,w3,w4,w5,w6,w7,w8,w9,w10) #changed last two to w11 and first to w3 

#######
#
# Calculate the total weight through a sum of fractional weights
# 
# Center Carp Population Estimates: 2941 - 6466 - 9990
# Center Buff Population Estimates: 1437 - 3529 - 5622
# Center Lake area: 220 acres
#
# Convert to lbs
# convert to density
#
# Should end up with a list of 6 (six) blue lake values (L.BM,BM,U.BM,L.BMDensity,BMDensity,U.BMDensity)

Center.COC.50$percent<-Center.COC.50$percent/100 # percent to decimal

Center.COC.50$LowerBM<-Center.COC.50$percent * Center.COC.50$mweight * 2941 # multiply fraction, mean weight, lower pop.
C.L.BM<-sum(Center.COC.50$LowerBM/453.592)


Center.COC.50$BMest<-Center.COC.50$percent * Center.COC.50$mweight * 6466 # multiply fraction, mean weight, pop. est
C.BM<-sum(Center.COC.50$BMest/453.592)

Center.COC.50$UpperBM<-Center.COC.50$percent * Center.COC.50$mweight * 9990 # multiply fraction, mean weight, upper pop.
C.U.BM<-sum(Center.COC.50$UpperBM/453.592)

C.L.BMDensity<-C.L.BM/220
C.BMDensity<-C.BM/220
C.U.BMDensity<-C.U.BM/220

# now buffalo
Center.bib.50$percent<-Center.bib.50$percent/100
Center.bib.50$LowerBM<-Center.bib.50$percent * Center.bib.50$mweight * 1437 # multiply fraction, mean weight, lower pop.
B.L.BM<-sum(Center.bib.50$LowerBM/453.592)

Center.bib.50$BMest<-Center.bib.50$percent * Center.bib.50$mweight * 3529 # multiply fraction, mean weight, pop. est
B.BM<-sum(Center.bib.50$BMest/453.592)

Center.bib.50$UpperBM<-Center.bib.50$percent * Center.bib.50$mweight * 5622 # multiply fraction, mean weight, upper pop.
B.U.BM<-sum(Center.bib.50$UpperBM/453.592)

B.L.BMDensity<-B.L.BM/220
B.BMDensity<-B.BM/220
B.U.BMDensity<-B.U.BM/220



Center.BM.Density<-c(C.L.BM,C.BM,C.U.BM,C.L.BMDensity,C.BMDensity,C.U.BMDensity,
                   B.L.BM,B.BM,B.U.BM,B.L.BMDensity,B.BMDensity,B.U.BMDensity)



```

#Five Island
```{r,}

###########################
#
# FiveIsland Lake
#
# Carp:
FiveIsland.coc<-subset(FiveIsland, Species =="COC")
FiveIsland.coc<-subset(FiveIsland.coc, !is.na(FiveIsland.coc$Length..mm.))
#Buffalo
FiveIsland.bib<-subset(FiveIsland, Species =="BIB")
FiveIsland.bib<-subset(FiveIsland.bib, !is.na(FiveIsland.bib$Length..mm.))
#25mm bins
FiveIsland.COC.25 <- FiveIsland.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
FiveIsland.COC.50 <- FiveIsland.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
# so now we have percent frequency in 25/50mm (1-2") bins. Need to calculate average weight for those bins.
# I forsee my method taking too long but it's all I can think of right now:
#       to reduce repitition, let's go with the 50mm (2") bins first.
#       need 1 line of code to subset a new frame for each length bin, 
#       then take mean weight.

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w2<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w3<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w4<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w5<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w6<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w7<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w8<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w9<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w10<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w11<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 800 & Length..mm. < 850 & !is.na(Weight..g.))
w12<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.coc.temp<-subset(FiveIsland.coc, Length..mm. >= 850 & Length..mm. < 900 & !is.na(Weight..g.))
w13<-mean(FiveIsland.coc.temp$Weight..g.)

FiveIsland.COC.50$mweight<-c(w3,w3,w4,w5,w6,w7,w8,w9,w10,w11,w11,w11) #changed last two to w11 and first to w3 

# Now Buffalo

#25mm bins
FiveIsland.bib.25 <- FiveIsland.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
FiveIsland.bib.50 <- FiveIsland.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()

#FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
#w1<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w2<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w3<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w4<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w5<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w6<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w7<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w8<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w9<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w10<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 800 & Length..mm. < 850 & !is.na(Weight..g.))
w11<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.temp<-subset(FiveIsland.bib, Length..mm. >= 850 & Length..mm. < 900 & !is.na(Weight..g.))
w12<-mean(FiveIsland.bib.temp$Weight..g.)

FiveIsland.bib.50$mweight<-c(w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w11) #changed last two to w11


#######
#
# Calculate the total weight through a sum of fractional weights
# 
# FiveIsland Carp Population Estimates: 19573 - 25798 - 32023
# FiveIsland Buff Population Estimates: -281 - 2300 - 4882
# FiveIsland Lake area: 973 acres
#
# Convert to lbs
# convert to density
#
# Should end up with a list of 6 (six) blue lake values (L.BM,BM,U.BM,L.BMDensity,BMDensity,U.BMDensity)

FiveIsland.COC.50$percent<-FiveIsland.COC.50$percent/100 # percent to decimal

FiveIsland.COC.50$LowerBM<-FiveIsland.COC.50$percent * FiveIsland.COC.50$mweight * 19573 # multiply fraction, mean weight, lower pop.
C.L.BM<-sum(FiveIsland.COC.50$LowerBM/453.592)


FiveIsland.COC.50$BMest<-FiveIsland.COC.50$percent * FiveIsland.COC.50$mweight * 25798 # multiply fraction, mean weight, pop. est
C.BM<-sum(FiveIsland.COC.50$BMest/453.592)

FiveIsland.COC.50$UpperBM<-FiveIsland.COC.50$percent * FiveIsland.COC.50$mweight * 32023 # multiply fraction, mean weight, upper pop.
C.U.BM<-sum(FiveIsland.COC.50$UpperBM/453.592)

C.L.BMDensity<-C.L.BM/973
C.BMDensity<-C.BM/973
C.U.BMDensity<-C.U.BM/973

# now buffalo
FiveIsland.bib.50$percent<-FiveIsland.bib.50$percent/100
FiveIsland.bib.50$LowerBM<-FiveIsland.bib.50$percent * FiveIsland.bib.50$mweight * -281 # multiply fraction, mean weight, lower pop.
B.L.BM<-sum(FiveIsland.bib.50$LowerBM/453.592)

FiveIsland.bib.50$BMest<-FiveIsland.bib.50$percent * FiveIsland.bib.50$mweight * 2300 # multiply fraction, mean weight, pop. est
B.BM<-sum(FiveIsland.bib.50$BMest/453.592)

FiveIsland.bib.50$UpperBM<-FiveIsland.bib.50$percent * FiveIsland.bib.50$mweight * 4882 # multiply fraction, mean weight, upper pop.
B.U.BM<-sum(FiveIsland.bib.50$UpperBM/453.592)

B.L.BMDensity<-B.L.BM/973
B.BMDensity<-B.BM/973
B.U.BMDensity<-B.U.BM/973



FiveIsland.BM.Density<-data.frame(cbind(C.L.BM,C.BM,C.U.BM,C.L.BMDensity,C.BMDensity,C.U.BMDensity,
                   B.L.BM,B.BM,B.U.BM,B.L.BMDensity,B.BMDensity,B.U.BMDensity))




```

# North Twin
```{r,}

###########################
#
# NTwin Lake
#
# Carp:
NTwin.coc<-subset(NTwin, Species =="COC")
NTwin.coc<-subset(NTwin.coc, !is.na(NTwin.coc$Length..mm.))
#Buffalo
NTwin.bib<-subset(NTwin, Species =="BIB")
NTwin.bib<-subset(NTwin.bib, !is.na(NTwin.bib$Length..mm.))
#25mm bins
NTwin.COC.25 <- NTwin.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
NTwin.COC.50 <- NTwin.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
# so now we have percent frequency in 25/50mm (1-2") bins. Need to calculate average weight for those bins.
# I forsee my method taking too long but it's all I can think of right now:
#       to reduce repitition, let's go with the 50mm (2") bins first.
#       need 1 line of code to subset a new frame for each length bin, 
#       then take mean weight.

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w4<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w5<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w6<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w7<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w8<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w9<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w10<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w11<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w12<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w13<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 800 & Length..mm. < 850 & !is.na(Weight..g.))
w14<-mean(NTwin.coc.temp$Weight..g.)

NTwin.coc.temp<-subset(NTwin.coc, Length..mm. >= 850 & Length..mm. < 900 & !is.na(Weight..g.))
w15<-mean(NTwin.coc.temp$Weight..g.)

NTwin.COC.50$mweight<-c(w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,w14,w15)

# Now Buffalo

#25mm bins
NTwin.bib.25 <- NTwin.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
NTwin.bib.50 <- NTwin.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 50 & Length..mm. < 100 & !is.na(Weight..g.))
w1<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 100 & Length..mm. < 150 & !is.na(Weight..g.))
w2<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 150 & Length..mm. < 200 & !is.na(Weight..g.))
w3<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w4<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w5<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w6<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w7<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w8<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w9<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w10<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w11<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w12<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 800 & Length..mm. < 850 & !is.na(Weight..g.))
w13<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 850 & Length..mm. < 900 & !is.na(Weight..g.))
w14<-mean(NTwin.bib.temp$Weight..g.)

NTwin.bib.temp<-subset(NTwin.bib, Length..mm. >= 900 & Length..mm. < 950 & !is.na(Weight..g.))
w15<-mean(NTwin.bib.temp$Weight..g.)


NTwin.bib.50$mweight<-c(w2,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,w13,w13) #changed last two to w11 and first to w3 

#######
#
# Calculate the total weight through a sum of fractional weights
# 
# NTwin Carp Population Estimates: 1942 - 3816 - 5690
# NTwin Buff Population Estimates: 8542 - 18776 - 29009
# NTwin Lake area: 453 acres
#
# Convert to lbs
# convert to density
#
# Should end up with a list of 6 (six) blue lake values (L.BM,BM,U.BM,L.BMDensity,BMDensity,U.BMDensity)

NTwin.COC.50$percent<-NTwin.COC.50$percent/100 # percent to decimal

NTwin.COC.50$LowerBM<-NTwin.COC.50$percent * NTwin.COC.50$mweight * 1942 # multiply fraction, mean weight, lower pop.
C.L.BM<-sum(NTwin.COC.50$LowerBM/453.592)


NTwin.COC.50$BMest<-NTwin.COC.50$percent * NTwin.COC.50$mweight * 3816 # multiply fraction, mean weight, pop. est
C.BM<-sum(NTwin.COC.50$BMest/453.592)

NTwin.COC.50$UpperBM<-NTwin.COC.50$percent * NTwin.COC.50$mweight * 5690 # multiply fraction, mean weight, upper pop.
C.U.BM<-sum(NTwin.COC.50$UpperBM/453.592)

C.L.BMDensity<-C.L.BM/453
C.BMDensity<-C.BM/453
C.U.BMDensity<-C.U.BM/453

# now buffalo
NTwin.bib.50$percent<-NTwin.bib.50$percent/100
NTwin.bib.50$LowerBM<-NTwin.bib.50$percent * NTwin.bib.50$mweight * 8542 # multiply fraction, mean weight, lower pop.
B.L.BM<-sum(NTwin.bib.50$LowerBM/453.592)

NTwin.bib.50$BMest<-NTwin.bib.50$percent * NTwin.bib.50$mweight * 18776 # multiply fraction, mean weight, pop. est
B.BM<-sum(NTwin.bib.50$BMest/453.592)

NTwin.bib.50$UpperBM<-NTwin.bib.50$percent * NTwin.bib.50$mweight * 29009 # multiply fraction, mean weight, upper pop.
B.U.BM<-sum(NTwin.bib.50$UpperBM/453.592)

B.L.BMDensity<-B.L.BM/453
B.BMDensity<-B.BM/453
B.U.BMDensity<-B.U.BM/453



NTwin.BM.Density<-data.frame(cbind(C.L.BM,C.BM,C.U.BM,C.L.BMDensity,C.BMDensity,C.U.BMDensity,
                   B.L.BM,B.BM,B.U.BM,B.L.BMDensity,B.BMDensity,B.U.BMDensity))

```

#Silver
```{r,}

###########################
#
# Silver Lake
#
# Carp:
Silver.coc<-subset(Silver, Species =="COC")
Silver.coc<-subset(Silver.coc, !is.na(Silver.coc$Length..mm.))
#Buffalo
Silver.bib<-subset(Silver, Species =="BIB")
Silver.bib<-subset(Silver.bib, !is.na(Silver.bib$Length..mm.))
#25mm bins
Silver.COC.25 <- Silver.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
Silver.COC.50 <- Silver.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
# so now we have percent frequency in 25/50mm (1-2") bins. Need to calculate average weight for those bins.
# I forsee my method taking too long but it's all I can think of right now:
#       to reduce repitition, let's go with the 50mm (2") bins first.
#       need 1 line of code to subset a new frame for each length bin, 
#       then take mean weight.

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 50 & Length..mm. < 100 & !is.na(Weight..g.))
w1<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 250 & Length..mm. < 300 & !is.na(Weight..g.))
w2<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w3<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w4<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w5<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w6<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w7<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w8<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w9<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w10<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w11<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w12<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 800 & Length..mm. < 850 & !is.na(Weight..g.))
w13<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 850 & Length..mm. < 900 & !is.na(Weight..g.))
w14<-mean(Silver.coc.temp$Weight..g.)

Silver.coc.temp<-subset(Silver.coc, Length..mm. >= 900 & Length..mm. < 950 & !is.na(Weight..g.))
w15<-mean(Silver.coc.temp$Weight..g.)

Silver.COC.50$mweight<-c(w2,w2,w3,w3,w3,w8,w8,w8,w9,w10,w11,w12,w13,w14,w14)

# Now Buffalo

#25mm bins
Silver.bib.25 <- Silver.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
Silver.bib.50 <- Silver.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 250 & Length..mm. < 300 & !is.na(Weight..g.))
w1<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w2<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w3<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w4<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w5<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w6<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w7<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w8<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w9<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w10<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w11<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 800 & Length..mm. < 850 & !is.na(Weight..g.))
w12<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.temp<-subset(Silver.bib, Length..mm. >= 850 & Length..mm. < 900 & !is.na(Weight..g.))
w13<-mean(Silver.bib.temp$Weight..g.)

Silver.bib.50$mweight<-c(w1,w2,w3,w5,w5,w6,w7,w8,w9,w10,w11,w12,w12) 

#######
#
# Calculate the total weight through a sum of fractional weights
# 
# Silver Carp Population Estimates: 6651 - 9755 - 12858
# Silver Buff Population Estimates: -9096 - 12486 - 34068
# Silver Lake area: 1041 acres
#
# Convert to lbs
# convert to density
#
# Should end up with a list of 6 (six) blue lake values (L.BM,BM,U.BM,L.BMDensity,BMDensity,U.BMDensity)

Silver.COC.50$percent<-Silver.COC.50$percent/100 # percent to decimal

Silver.COC.50$LowerBM<-Silver.COC.50$percent * Silver.COC.50$mweight * 6651 # multiply fraction, mean weight, lower pop.
C.L.BM<-sum(Silver.COC.50$LowerBM/453.592)


Silver.COC.50$BMest<-Silver.COC.50$percent * Silver.COC.50$mweight * 9755 # multiply fraction, mean weight, pop. est
C.BM<-sum(Silver.COC.50$BMest/453.592)

Silver.COC.50$UpperBM<-Silver.COC.50$percent * Silver.COC.50$mweight * 12858 # multiply fraction, mean weight, upper pop.
C.U.BM<-sum(Silver.COC.50$UpperBM/453.592)

C.L.BMDensity<-C.L.BM/1041
C.BMDensity<-C.BM/1041
C.U.BMDensity<-C.U.BM/1041

# now buffalo
Silver.bib.50$percent<-Silver.bib.50$percent/100
Silver.bib.50$LowerBM<-Silver.bib.50$percent * Silver.bib.50$mweight * -9096 # multiply fraction, mean weight, lower pop.
B.L.BM<-sum(Silver.bib.50$LowerBM/453.592)

Silver.bib.50$BMest<-Silver.bib.50$percent * Silver.bib.50$mweight * 12486 # multiply fraction, mean weight, pop. est
B.BM<-sum(Silver.bib.50$BMest/453.592)

Silver.bib.50$UpperBM<-Silver.bib.50$percent * Silver.bib.50$mweight * 34068 # multiply fraction, mean weight, upper pop.
B.U.BM<-sum(Silver.bib.50$UpperBM/453.592)

B.L.BMDensity<-C.L.BM/1041
B.BMDensity<-C.BM/1041
B.U.BMDensity<-B.U.BM/1041



Silver.BM.Density<-data.frame(cbind(C.L.BM,C.BM,C.U.BM,C.L.BMDensity,C.BMDensity,C.U.BMDensity,
                   B.L.BM,B.BM,B.U.BM,B.L.BMDensity,B.BMDensity,B.U.BMDensity))
```

#South Twin
```{r,}

###########################
#
# STwin Lake
#
# Carp:
STwin.coc<-subset(STwin, Species =="COC")
STwin.coc<-subset(STwin.coc, !is.na(STwin.coc$Length..mm.))
#Buffalo
STwin.bib<-subset(STwin, Species =="BIB")
STwin.bib<-subset(STwin.bib, !is.na(STwin.bib$Length..mm.))
#25mm bins
STwin.COC.25 <- STwin.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
STwin.COC.50 <- STwin.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
# so now we have percent frequency in 25/50mm (1-2") bins. Need to calculate average weight for those bins.
# I forsee my method taking too long but it's all I can think of right now:
#       to reduce repitition, let's go with the 50mm (2") bins first.
#       need 1 line of code to subset a new frame for each length bin, 
#       then take mean weight.

#STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 50 & Length..mm. < 100 & !is.na(Weight..g.))
#w1<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 250 & Length..mm. < 300 & !is.na(Weight..g.))
w1<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w2<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w3<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w4<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w5<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w6<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w7<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w8<-mean(STwin.coc.temp$Weight..g.)

#STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
#w10<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w9<-mean(STwin.coc.temp$Weight..g.)

STwin.coc.temp<-subset(STwin.coc, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w10<-mean(STwin.coc.temp$Weight..g.)

STwin.COC.50$mweight<-c(w1,w2,w3,w4,w5,w6,w6,w9,w9,w9)

# Now Buffalo

#25mm bins
STwin.bib.25 <- STwin.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
STwin.bib.50 <- STwin.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()

#STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 250 & Length..mm. < 300 & !is.na(Weight..g.))
#w1<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w1<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w2<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w3<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w4<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w5<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w6<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w7<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w8<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w9<-mean(STwin.bib.temp$Weight..g.)

STwin.bib.temp<-subset(STwin.bib, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w10<-mean(STwin.bib.temp$Weight..g.)


STwin.bib.50$mweight<-c(w2,w2,w3,w4,w5,w6,w7,w7,w7,w7) 

#######
#
# Calculate the total weight through a sum of fractional weights
# 
# STwin Carp Population Estimates: 13001 - 20661 - 28320
# STwin Buff Population Estimates: 18839 - 34277 - 49715
# STwin Lake area: 600 acres
#
# Convert to lbs
# convert to density
#
# Should end up with a list of 6 (six) blue lake values (L.BM,BM,U.BM,L.BMDensity,BMDensity,U.BMDensity)

STwin.COC.50$percent<-STwin.COC.50$percent/100 # percent to decimal

STwin.COC.50$LowerBM<-STwin.COC.50$percent * STwin.COC.50$mweight * 13001 # multiply fraction, mean weight, lower pop.
C.L.BM<-sum(STwin.COC.50$LowerBM/453.592)


STwin.COC.50$BMest<-STwin.COC.50$percent * STwin.COC.50$mweight * 20661 # multiply fraction, mean weight, pop. est
C.BM<-sum(STwin.COC.50$BMest/453.592)

STwin.COC.50$UpperBM<-STwin.COC.50$percent * STwin.COC.50$mweight * 28320 # multiply fraction, mean weight, upper pop.
C.U.BM<-sum(STwin.COC.50$UpperBM/453.592)

C.L.BMDensity<-C.L.BM/600
C.BMDensity<-C.BM/600
C.U.BMDensity<-C.U.BM/600

# now buffalo
STwin.bib.50$percent<-STwin.bib.50$percent/100
STwin.bib.50$LowerBM<-STwin.bib.50$percent * STwin.bib.50$mweight * 18839 # multiply fraction, mean weight, lower pop.
B.L.BM<-sum(STwin.bib.50$LowerBM/453.592)

STwin.bib.50$BMest<-STwin.bib.50$percent * STwin.bib.50$mweight * 34227 # multiply fraction, mean weight, pop. est
B.BM<-sum(STwin.bib.50$BMest/453.592)

STwin.bib.50$UpperBM<-STwin.bib.50$percent * STwin.bib.50$mweight * 49715 # multiply fraction, mean weight, upper pop.
B.U.BM<-sum(STwin.bib.50$UpperBM/453.592)

B.L.BMDensity<-B.L.BM/600
B.BMDensity<-B.BM/600
B.U.BMDensity<-B.U.BM/600



STwin.BM.Density<-data.frame(cbind(C.L.BM,C.BM,C.U.BM,C.L.BMDensity,C.BMDensity,C.U.BMDensity,
                   B.L.BM,B.BM,B.U.BM,B.L.BMDensity,B.BMDensity,B.U.BMDensity))
```

#Storm
```{r,}

###########################
#
# Storm Lake
#
# Carp:
Storm.coc<-subset(Storm, Species =="COC")
Storm.coc<-subset(Storm.coc, !is.na(Storm.coc$Length..mm.))
#Buffalo
Storm.bib<-subset(Storm, Species =="BIB")
Storm.bib<-subset(Storm.bib, !is.na(Storm.bib$Length..mm.))
#25mm bins
Storm.COC.25 <- Storm.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
Storm.COC.50 <- Storm.coc %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
# so now we have percent frequency in 25/50mm (1-2") bins. Need to calculate average weight for those bins.
# I forsee my method taking too long but it's all I can think of right now:
#       to reduce repitition, let's go with the 50mm (2") bins first.
#       need 1 line of code to subset a new frame for each length bin, 
#       then take mean weight.

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 150 & Length..mm. < 200 & !is.na(Weight..g.))
w1<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 250 & Length..mm. < 300 & !is.na(Weight..g.))
w2<-mean(Storm.coc.temp$Weight..g.)

#Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
#w2<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w3<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w4<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w5<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w6<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w7<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w8<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w9<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w10<-mean(Storm.coc.temp$Weight..g.)

Storm.coc.temp<-subset(Storm.coc, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w11<-mean(Storm.coc.temp$Weight..g.)

Storm.COC.50$mweight<-c(w3,w3,w3,w4,w5,w6,w7,w8,w9,w10,w10)

# Now Buffalo

#25mm bins
Storm.bib.25 <- Storm.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=25))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()
#50mm bins
Storm.bib.50 <- Storm.bib %>%
  add_count(Species) %>%
  rename(Species_count = n) %>%
  group_by(Species, Species_count, gr=cut(Length..mm., breaks = seq(0,1000,by=50))) %>%
  summarise(n = n()) %>%
  mutate(freq=n, percent = ((n/Species_count)*100),
         cumfreq = cumsum(freq), cumpercent = cumsum(percent)) %>%
  ungroup()

#Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 250 & Length..mm. < 300 & !is.na(Weight..g.))
#w1<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 300 & Length..mm. < 350 & !is.na(Weight..g.))
w1<-mean(Storm.bib.temp$Weight..g.) #NaN

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 350 & Length..mm. < 400 & !is.na(Weight..g.))
w2<-mean(Storm.bib.temp$Weight..g.) #NaN

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 400 & Length..mm. < 450 & !is.na(Weight..g.))
w3<-mean(Storm.bib.temp$Weight..g.) #NaN

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 450 & Length..mm. < 500 & !is.na(Weight..g.))
w4<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 500 & Length..mm. < 550 & !is.na(Weight..g.))
w5<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 550 & Length..mm. < 600 & !is.na(Weight..g.))
w6<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 600 & Length..mm. < 650 & !is.na(Weight..g.))
w7<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 650 & Length..mm. < 700 & !is.na(Weight..g.))
w8<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 700 & Length..mm. < 750 & !is.na(Weight..g.))
w9<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 750 & Length..mm. < 800 & !is.na(Weight..g.))
w10<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 800 & Length..mm. < 850 & !is.na(Weight..g.))
w11<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 850 & Length..mm. < 900 & !is.na(Weight..g.))
w12<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 900 & Length..mm. < 950 & !is.na(Weight..g.))
w13<-mean(Storm.bib.temp$Weight..g.)

Storm.bib.temp<-subset(Storm.bib, Length..mm. >= 950 & Length..mm. < 1000 & !is.na(Weight..g.))
w14<-mean(Storm.bib.temp$Weight..g.) #NaN

Storm.bib.50$mweight<-c(w4,w4,w4,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,w13) 

#######
#
# Calculate the total weight through a sum of fractional weights
# 
# Storm Carp Population Estimates: 6984 - 9251 - 11518
# Storm Buff Population Estimates: -66973 - 13724 - 94421
# Storm Lake area: 3097 acres
#
# Convert to lbs
# convert to density
#
# Should end up with a list of 6 (six) blue lake values (L.BM,BM,U.BM,L.BMDensity,BMDensity,U.BMDensity)

Storm.COC.50$percent<-Storm.COC.50$percent/100 # percent to decimal

Storm.COC.50$LowerBM<-Storm.COC.50$percent * Storm.COC.50$mweight * 6984 # multiply fraction, mean weight, lower pop.
C.L.BM<-sum(Storm.COC.50$LowerBM/453.592)


Storm.COC.50$BMest<-Storm.COC.50$percent * Storm.COC.50$mweight * 9251 # multiply fraction, mean weight, pop. est
C.BM<-sum(Storm.COC.50$BMest/453.592)

Storm.COC.50$UpperBM<-Storm.COC.50$percent * Storm.COC.50$mweight * 11518 # multiply fraction, mean weight, upper pop.
C.U.BM<-sum(Storm.COC.50$UpperBM/453.592)

C.L.BMDensity<-C.L.BM/3097
C.BMDensity<-C.BM/3097
C.U.BMDensity<-C.U.BM/3097

# now buffalo
Storm.bib.50$percent<-Storm.bib.50$percent/100
Storm.bib.50$LowerBM<-Storm.bib.50$percent * Storm.bib.50$mweight * -66973 # multiply fraction, mean weight, lower pop.
B.L.BM<-sum(Storm.bib.50$LowerBM/453.592)

Storm.bib.50$BMest<-Storm.bib.50$percent * Storm.bib.50$mweight * 13724 # multiply fraction, mean weight, pop. est
B.BM<-sum(Storm.bib.50$BMest/453.592)

Storm.bib.50$UpperBM<-Storm.bib.50$percent * Storm.bib.50$mweight * 94421 # multiply fraction, mean weight, upper pop.
B.U.BM<-sum(Storm.bib.50$UpperBM/453.592)

B.L.BMDensity<-B.L.BM/3097
B.BMDensity<-B.BM/3097
B.U.BMDensity<-B.U.BM/3097



Storm.BM.Density<-data.frame(cbind(C.L.BM,C.BM,C.U.BM,C.L.BMDensity,C.BMDensity,C.U.BMDensity,
                   B.L.BM,B.BM,B.U.BM,B.L.BMDensity,B.BMDensity,B.U.BMDensity))
```

# Bring it all together for total biomass and biomass density

```{r,}
# Rbind each of the 7 lists of twelve (data frames)

All.biomass<-rbind(Blue.BM.Density,
                   Center.BM.Density,
                   FiveIsland.BM.Density,
                   NTwin.BM.Density,
                   Silver.BM.Density,
                   STwin.BM.Density,
                   Storm.BM.Density)


```