---
title: "AECL 520 Group Project"
author: "Martin Simonson"
date: "April 12, 2019"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

Here I am taking output data from FAMS von bert curves and our analyses of mean length of fish caught compared to the different length limits.

idea is to get figures in a panel grid (vertical?)

-- read in data

```{r}
df<-read.csv("AECL520/NewFams.csv", header = T )
str(df)
df$Min.Length.Limit<-factor(df$Min.Length.Limit)
```


-- plot some figs

```{r}
library(ggplot2)
library(gridExtra)
library(reshape2)

# removing survival and recruitment 

df.m<-melt(df, id.vars = c("Min.Length.Limit","Exploitation"))
ggplot(df.m, aes (x = Exploitation,y = value, group = Min.Length.Limit, colour = Min.Length.Limit))+
  theme_classic()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill="white",colour="grey50"), 
        axis.line = element_line(colour = "black"),
        legend.position = "bottom",
        legend.background = element_rect(colour="grey20"))+
  geom_line(size = 1.25)+
  geom_point(size = 2)+
  labs(title = "Estimated Crappie Harvest as a Function of Exploitation",
       subtitle = "Considering three different minimum length limits",
       y = "")+
  facet_grid(variable~., scales = "free_y")


# removing survival and time to recruitment, this way we have three panels that each show a different harvest goal
df2<-df[,-c(2,3)]
df.m2<-melt(df2, id.vars = c("Min.TL..mm.","Exploitation"))
ggplot(df.m2, aes (x = Exploitation,y = value, group = Min.TL..mm., colour = Min.TL..mm., shape = Min.TL..mm.))+
  theme_classic()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill="white",colour="grey50"), 
        axis.line = element_line(colour = "black"),
        legend.position = "bottom",
        legend.background = element_rect(colour="grey20"))+
  geom_line(size = 1.25)+
  geom_point(size = 3)+
  labs(title = "Estimated Crappie Harvest as a Function of Exploitation",
       subtitle = "Considering three different minimum length limits",
       y = "")+
  facet_grid(variable~., scales = "free_y")


```

new plots with American units and better labels, etc.

```{r}
head(df)
# change units
df$Min.Length.Limit<-as.numeric(as.character(df$Min.Length.Limit))
df$MinInches<-df$Min.Length.Limit/25.4
df$MeanInches<-df$Mean.Length.of.Fish.Caught/25.4
df$Min.Length.Limit<-as.factor(df$Min.Length.Limit)
df$MinInches<-as.factor(df$MinInches)
df$Yield.Pounds<-df$Yield..kg.*2.205

df3<-data.frame(as.numeric(as.character(df$MinInches)),
                           df$Exploitation,
                           df$Number.Harvested,
                           df$Yield.Pounds,
                           df$MeanInches)
head(df3)
colnames(df3)<-c("Minimum Length Limit (Inches)","Exploitation Rate","Number Harvested","Yield in Pounds","Average Length Caught")
df3$`Minimum Length Limit (Inches)`<-round(df3$`Minimum Length Limit (Inches)`)
df3$`Minimum Length Limit (Inches)`<-factor(df3$`Minimum Length Limit (Inches)`)


df.m3<-melt(df3, id.vars = c("Minimum Length Limit (Inches)","Exploitation Rate"))

require(scales)
scale_x_continuous(labels = comma)

ggplot(df.m3, aes (x = `Exploitation Rate`,
                   y = value, 
                   group = `Minimum Length Limit (Inches)`, 
                   colour = `Minimum Length Limit (Inches)`, 
                   shape = `Minimum Length Limit (Inches)`))+
  theme_classic()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill="white",colour="grey50"),
        axis.line = element_line(colour = "black"),
        legend.position = "bottom",
        legend.background = element_rect(colour="grey20"))+
  labs(fill = "Minimum Length Limit (Inches)")+
  geom_line(size = 1.25)+
  geom_point(size = 3)+
  scale_y_continuous(labels = comma)+
  labs(title = "Estimated Crappie Harvest as a Function of Exploitation",
       subtitle = "Considering three different minimum length limits",
       y = "")+
  facet_grid(variable~., scales = "free_y")










```

