---
title: "2020 rmark input file"
author: "Martin Simonson"
date: "2/5/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(RMark)
library(dplyr)
setwd("~/BMB-COC/MARK/2020")
dframe<-read.csv("2017-2020 Compiled Data.csv",header=T)
dframe$Date<-as.Date(dframe$Date, "%m/%d/%Y")
dframe$Year.Month<-factor(format(dframe$Date, "%Y.%m"))
dframe$Year<-factor(format(dframe$Date, "%Y"))

str(dframe)
```

# getting capture history together

```{r}
# for the moment, let's just do center lake 

# and for the moment buffalo only:

df<-droplevels(subset(dframe, Lake == "Center" &
                          Species == "BIB" &
                          !is.na(df$TAG.NUMBER)))
# remove dissections and others
df$TAG.NUMBER[df$TAG.NUMBER == ""]<-NA
df<-droplevels(subset(df, !is.na(as.numeric(as.character(df$TAG.NUMBER)))))
levels(df$Notes)



# condense to year and tag number and detect

df2<-df[,c(3,21,22)]


capt.hist<-df2 %>%
  # remove duplicates when fish are caught more than once in an event
  distinct() %>%
  # spread out data. Fill = 0 adds rows for combinations of ID and event w/o observations
  spread(Year, detect, fill = 0) %>%
  # for every individual
  group_by(TAG.NUMBER) %>%
  # paste together 0s and 1s
  # unite is similar to paste
  unite("ch",2:tail(names(.),1),sep = "")

# well that worked, now to make it a .inp file
c.b.ch.year<-capt.hist[,2] # code: Center.Buffalo.CaptureHistory.Year - capture histories of buff condensed to years

# making it work for months over years (robust design)
df2<-df[,c(3,23,22)]
capt.hist<-df2 %>%
  # remove duplicates when fish are caught more than once in an event
  distinct() %>%
  # spread out data. Fill = 0 adds rows for combinations of ID and event w/o observations
  spread(Year.Month, detect, fill = 0) %>%
  # for every individual
  group_by(TAG.NUMBER) %>%
  # paste together 0s and 1s
  # unite is similar to paste
  unite("ch",2:tail(names(.),1),sep = "")

# well that worked, now to make it a .inp file
c.b.ch.month<-capt.hist[,2] # code: Center.Buffalo.CaptureHistory.Month - capture histories of buff condensed to Months
c.b.ch.month$freq<-1

############
#
# Carp
#
###########
df<-droplevels(subset(dframe, Lake == "Center" &
                          Species == "COC" ))
# remove dissections and others
df$TAG.NUMBER[df$TAG.NUMBER == ""]<-NA
df<-droplevels(subset(df, !is.na(as.numeric(as.character(df$TAG.NUMBER)))))




# condense to year and tag number and detect

df2<-df[,c(3,21,22)]


capt.hist<-df2 %>%
  # remove duplicates when fish are caught more than once in an event
  distinct() %>%
  # spread out data. Fill = 0 adds rows for combinations of ID and event w/o observations
  spread(Year, detect, fill = 0) %>%
  # for every individual
  group_by(TAG.NUMBER) %>%
  # paste together 0s and 1s
  # unite is similar to paste
  unite("ch",2:tail(names(.),1),sep = "")

# well that worked, now to make it a .inp file
c.c.ch.year<-capt.hist[,2] # code: Center.Carp.CaptureHistory.Year - capture histories of carp condensed to years

# condense to tag number, month, and detect
df2<-df[,c(3,23,22)]
capt.hist<-df2 %>%
  # remove duplicates when fish are caught more than once in an event
  distinct() %>%
  # spread out data. Fill = 0 adds rows for combinations of ID and event w/o observations
  spread(Year.Month, detect, fill = 0) %>%
  # for every individual
  group_by(TAG.NUMBER) %>%
  # paste together 0s and 1s
  # unite is similar to paste
  unite("ch",2:tail(names(.),1),sep = "")

# well that worked, now to make it a .inp file
c.c.ch.month<-capt.hist[,2] # code: Center.Carp.CaptureHistory.Month - capture histories of carp condensed to months

# attempt at saving to try in MARK itself
write.csv(c.b.ch.month, "CenterBuffRD.inp",row.names = F)
```


# robust design models with monthly capture histories

```{r}
#Identify time intervals
levels(df2$Year.Month)

run.robust=function()
{
#
# data from Robust.dbf with MARK
# 5 primary sessions with secondary sessions of length 2,6,6
#
time.intervals=c(0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0)
#
#

rd <- process.data(data = c.b.ch.month,
                  model = "Robust",
                  time.intervals = time.intervals)
                  
names(rd)
rd$nocc
rd$nocc.secondary

S.time=list(formula=~time)
p.time.session=list(formula=~-1+session:time,share=TRUE)
model.1=mark(data = rd, model = "Robust", 
            time.intervals=time.intervals,
            model.parameters=list(S=S.time,
            p=p.time.session),threads=2)

S.time.session=list(formula=~1+session:time,share=TRUE)
p.time.session=list(formula=~1+session:time,share=TRUE)
model.2=mark(data = rd, model = "Robust",
             time.intervals=time.intervals,
             model.parameters=list(S=S.time,
                                   p=p.time.session),threads=2)
return(collect.models())
}
robust.results=run.robust()

robust.results
```

