---
title: "Ecostats Final Project"
author: "Martin Simonson"
date: "12/3/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd("~/BMB-COC")
df<-read.csv("2018/2018 Raw CPUE Data.csv", header = T)
str(df)

blue<-droplevels(subset(df, Lake == "Blue"))
blue<-blue[,-1]
str(blue)
head(blue)

blue$Date<-as.Date(with(df, paste(blue$Year,blue$Month,blue$Day, sep = "-")), "%Y-%m-%d")

blue2<-data.frame(blue$Date, blue$Run, blue$Effort, blue$n)
head(blue2)

effort<-aggregate(blue2["blue.Effort"], by = blue2["blue.Date"],sum)
catch<-aggregate(blue2["blue.n"], by = blue2["blue.Date"],sum)

cpue<-cbind(effort, catch$blue.n)
cpue

blue.cpue<-data.frame(cpue$blue.Date, cpue$`catch$blue.n`/cpue$blue.Effort)
colnames(blue.cpue)<- c("Date", "CPUE")
blue.cpue
```

# now to add environmental covariates
- water temp (data)
- noon air temp
- noon wind speed

```{r}
# water temps from data
watertemp<-read.csv("2018_COC_BIB_CMR_Data.csv")
watertemp<-droplevels(subset(watertemp, Lake == "Blue"))
watertemp<-watertemp[,c(1,18)]
summary(watertemp$Water.Temp..C.) # GREAT! non-existent data. Is there another way to get this?

# air temps from weather underground (farenheit at noon)
blue.cpue$AirTemp<-c(65,71,80,78,71,66,59,80,83,78,63,74,85,88,84,78,88,92,83,88,85,77,78,51,55,41)

# wind from weather underground (noon MPH)
blue.cpue$Wind<-c(10,13,16,5,18,14,16,10,13,18,6,13,18,5,9,9,15,14,18,13,8,9,7,7,16,12)

# changing farenheit to celcius
blue.cpue$AirTemp<-round((blue.cpue$AirTemp-32)*(5/9),1)
blue.cpue

# write csv
write.csv(blue.cpue, "Ecostats Project - CPUE.csv", row.names = F)
```

# North Twin 2018

```{r}

df<-read.csv("2018/2018 Raw CPUE Data.csv", header = T)
str(df)
# Despite objects being named 'blue' everything from this line onward is actually North Twin
blue<-droplevels(subset(df, Lake == "N. Twin"))
blue<-blue[,-1]
# and we need to split by species or add that variable....
levels(blue$Species)


str(blue)
head(blue)

blue$Date<-as.Date(with(df, paste(blue$Year,blue$Month,blue$Day, sep = "-")), "%Y-%m-%d")

blue2<-data.frame(blue$Date, blue$Run, blue$Effort, blue$n, blue$Species)
head(blue2)

effort<-aggregate(blue2["blue.Effort"], by = blue2[c("blue.Date","blue.Species")],sum)
catch<-aggregate(blue2["blue.n"], by = blue2[c("blue.Date","blue.Species")],sum)

cpue<-cbind(effort, catch$blue.n)
cpue

blue.cpue<-data.frame(cpue$blue.Date,cpue$blue.Species, cpue$`catch$blue.n`/cpue$blue.Effort)
colnames(blue.cpue)<- c("Date","Species", "CPUE")
ntwin.cpue<-blue.cpue
ntwin.cpue
```

## North Twin covariates

```{r}
# water temps from data
watertemp<-read.csv("2018_COC_BIB_CMR_Data.csv")
levels(watertemp$Lake)
levels(watertemp$Gear)
watertemp<-droplevels(subset(watertemp, Lake == "N. Twin"))
watertemp<-droplevels(subset(watertemp, Gear == "Electroshocking"))
watertemp<-watertemp[,c(1,4,18)]
watertemp<-droplevels(subset(watertemp, Species == "BIB" | Species == "COC"))
summary(watertemp$Water.Temp..C.) # GREAT! 
WaterTemp<-aggregate(watertemp["Water.Temp..C."], 
                     by = watertemp[c("Date","Species")],mean) # vector of length 17 here
# see if we can't paste that Ish to the CPUE dataframe
ntwin.cpue<-cbind(ntwin.cpue,WaterTemp)
ntwin.cpue
# see that dates and species match up, so we gone cut out cols 4 and 5
ntwin.cpue<-ntwin.cpue[,-c(4,5)]


# air temps from weather underground (farenheit at noon)
ntwin.cpue$AirTemp<-rep(c(72,80,81,81,85,88,79,78,81,77,82,86,73,73,48,41,55),2)

# wind from weather underground (noon MPH)
ntwin.cpue$Wind<-rep(c(7,6,17,3,9,8,5,5,14,5,8,17,8,7,18,7,3),2)

# changing farenheit to celcius
ntwin.cpue$AirTemp<-round((ntwin.cpue$AirTemp-32)*(5/9),1)
ntwin.cpue

# split by species, for two .csv data files
ntwin.18.cpue.coc<-droplevels(subset(ntwin.cpue, Species == "COC"))
ntwin.18.cpue.bib<-droplevels(subset(ntwin.cpue, Species == "BIB"))

# write csv files
write.csv(ntwin.18.cpue.bib, "NTwin18CPUEbuff.csv", row.names = F)
write.csv(ntwin.18.cpue.coc, "NTwin18CPUEcarp.csv", row.names = F)
```

